//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfg.Test
{
    public enum test1
    {
        /// <summary>
        /// 基础包
        /// </summary>
        Items = 1,
        /// <summary>
        /// 扩展包1
        /// </summary>
        Ver121 = 2,
        /// <summary>
        /// 扩展包2
        /// </summary>
        Ver300 = 3,
    }
}
